export const assets = [
  {
    "name": "bush_1",
    "total-height": 2,
    "total-width": 2,
    "footprint-height": 1,
    "footprint-width": 2,
    "footprint-offset": 0,
    "origin-x": 0,
    "origin-y": 0,
    "biome": ["grass"]
  },
  {
    "name": "bush_2",
    "total-height": 2,
    "total-width": 2,
    "footprint-height": 1,
    "footprint-width": 2,
    "footprint-offset": 0,
    "origin-x": 0,
    "origin-y": 2,
    "biome": ["grass"]
  },
  {
    "name": "bush_3",
    "total-height": 2,
    "total-width": 2,
    "footprint-height": 1,
    "footprint-width": 2,
    "footprint-offset": 0,
    "origin-x": 0,
    "origin-y": 4,
    "biome": ["grass"]
  },
  {
    "name": "bush_4",
    "total-height": 2,
    "total-width": 2,
    "footprint-height": 1,
    "footprint-width": 2,
    "footprint-offset": 0,
    "origin-x": 2,
    "origin-y": 0,
    "biome": ["grass"]
  },
  {
    "name": "bush_5",
    "total-height": 2,
    "total-width": 2,
    "footprint-height": 1,
    "footprint-width": 2,
    "footprint-offset": 0,
    "origin-x": 2,
    "origin-y": 2,
    "biome": ["grass"]
  },
  {
    "name": "bush_6",
    "total-height": 2,
    "total-width": 2,
    "footprint-height": 1,
    "footprint-width": 2,
    "footprint-offset": 0,
    "origin-x": 2,
    "origin-y": 4,
    "biome": ["grass"]
  },
  {
    "name": "bush_7",
    "total-height": 2,
    "total-width": 2,
    "footprint-height": 1,
    "footprint-width": 2,
    "footprint-offset": 0,
    "origin-x": 4,
    "origin-y": 0,
    "biome": ["grass"]
  },
  {
    "name": "bush_8",
    "total-height": 2,
    "total-width": 2,
    "footprint-height": 1,
    "footprint-width": 2,
    "footprint-offset": 0,
    "origin-x": 4,
    "origin-y": 2,
    "biome": ["grass"]
  },
  {
    "name": "bush_9",
    "total-height": 2,
    "total-width": 2,
    "footprint-height": 1,
    "footprint-width": 2,
    "footprint-offset": 0,
    "origin-x": 4,
    "origin-y": 4,
    "biome": ["grass"]
  },
  {
    "name": "bush_10",
    "total-height": 2,
    "total-width": 2,
    "footprint-height": 1,
    "footprint-width": 2,
    "footprint-offset": 0,
    "origin-x": 6,
    "origin-y": 0,
    "biome": ["grass"]
  },
  {
    "name": "bush_11",
    "total-height": 2,
    "total-width": 2,
    "footprint-height": 1,
    "footprint-width": 2,
    "footprint-offset": 0,
    "origin-x": 6,
    "origin-y": 2,
    "biome": ["dirt"]
  },
  {
    "name": "bush_12",
    "total-height": 2,
    "total-width": 2,
    "footprint-height": 1,
    "footprint-width": 2,
    "footprint-offset": 0,
    "origin-x": 6,
    "origin-y": 4,
    "biome": ["dirt"]
  },
  {
    "name": "tree_1",
    "total-height": 4,
    "total-width": 3,
    "footprint-height": 1,
    "footprint-width": 3,
    "footprint-offset": 0,
    "origin-x": 8,
    "origin-y": 0,
    "biome": ["grass"]
  },
  {
    "name": "tree_2",
    "total-height": 5,
    "total-width": 4,
    "footprint-height": 1,
    "footprint-width": 2,
    "footprint-offset": 1,
    "origin-x": 11,
    "origin-y": 0,
    "biome": ["grass"]
  },
  {
    "name": "tree_3",
    "total-height": 8,
    "total-width": 5,
    "footprint-height": 2,
    "footprint-width": 4,
    "footprint-offset": 0,
    "origin-x": 0,
    "origin-y": 9,
    "biome": ["grass"]
  },
  {
    "name": "tree_4",
    "total-height": 7,
    "total-width": 5,
    "footprint-height": 2,
    "footprint-width": 4,
    "footprint-offset": 0,
    "origin-x": 5,
    "origin-y": 10,
    "biome": ["grass"]
  },
  {
    "name": "tree_5",
    "total-height": 7,
    "total-width": 5,
    "footprint-height": 2,
    "footprint-width": 3,
    "footprint-offset": 1,
    "origin-x": 10,
    "origin-y": 10,
    "biome": ["grass"]
  },
  {
    "name": "flower_1",
    "total-height": 1,
    "total-width": 1,
    "footprint-height": 1,
    "footprint-width": 1,
    "footprint-offset": 0,
    "origin-x": 8,
    "origin-y": 4,
    "biome": ["grass"]
  },
  {
    "name": "flower_2",
    "total-height": 1,
    "total-width": 1,
    "footprint-height": 1,
    "footprint-width": 1,
    "footprint-offset": 0,
    "origin-x": 8,
    "origin-y": 5,
    "biome": ["grass"]
  },
  {
    "name": "flower_3",
    "total-height": 1,
    "total-width": 2,
    "footprint-height": 1,
    "footprint-width": 2,
    "footprint-offset": 0,
    "origin-x": 9,
    "origin-y": 4,
    "biome": ["grass"]
  },
  {
    "name": "flower_4",
    "total-height": 1,
    "total-width": 2,
    "footprint-height": 1,
    "footprint-width": 2,
    "footprint-offset": 0,
    "origin-x": 9,
    "origin-y": 5,
    "biome": ["grass"]
  },
  {
    "name": "shrub_1",
    "total-height": 3,
    "total-width": 2,
    "footprint-height": 1,
    "footprint-width": 2,
    "footprint-offset": 0,
    "origin-x": 0,
    "origin-y": 6,
    "biome": ["grass"]
  },
  {
    "name": "shrub_2",
    "total-height": 3,
    "total-width": 2,
    "footprint-height": 1,
    "footprint-width": 2,
    "footprint-offset": 0,
    "origin-x": 2,
    "origin-y": 6,
    "biome": ["grass"]
  },
  {
    "name": "shrub_3",
    "total-height": 3,
    "total-width": 2,
    "footprint-height": 1,
    "footprint-width": 2,
    "footprint-offset": 0,
    "origin-x": 4,
    "origin-y": 6,
    "biome": ["grass"]
  },
  {
    "name": "shrub_4",
    "total-height": 2,
    "total-width": 2,
    "footprint-height": 1,
    "footprint-width": 2,
    "footprint-offset": 0,
    "origin-x": 6,
    "origin-y": 6,
    "biome": ["grass"]
  },
  {
    "name": "shrub_5",
    "total-height": 2,
    "total-width": 2,
    "footprint-height": 1,
    "footprint-width": 2,
    "footprint-offset": 0,
    "origin-x": 8,
    "origin-y": 6,
    "biome": ["grass"]
  },
  {
    "name": "shrub_6",
    "total-height": 2,
    "total-width": 2,
    "footprint-height": 1,
    "footprint-width": 2,
    "footprint-offset": 0,
    "origin-x": 10,
    "origin-y": 6,
    "biome": ["grass"]
  },
  {
    "name": "mushroom_1",
    "total-height": 1,
    "total-width": 1,
    "footprint-height": 1,
    "footprint-width": 1,
    "footprint-offset": 0,
    "origin-x": 15,
    "origin-y": 0,
    "biome": ["grass"]
  },
  {
    "name": "mushroom_2",
    "total-height": 1,
    "total-width": 1,
    "footprint-height": 1,
    "footprint-width": 1,
    "footprint-offset": 0,
    "origin-x": 15,
    "origin-y": 1,
    "biome": ["grass"]
  },
  {
    "name": "mushroom_3",
    "total-height": 1,
    "total-width": 1,
    "footprint-height": 1,
    "footprint-width": 1,
    "footprint-offset": 0,
    "origin-x": 15,
    "origin-y": 2,
    "biome": ["grass"]
  },
  {
    "name": "mushroom_4",
    "total-height": 1,
    "total-width": 1,
    "footprint-height": 1,
    "footprint-width": 1,
    "footprint-offset": 0,
    "origin-x": 15,
    "origin-y": 3,
    "biome": ["grass"]
  },
  {
    "name": "water_lily_1",
    "total-height": 2,
    "total-width": 2,
    "footprint-height": 1,
    "footprint-width": 2,
    "footprint-offset": 0,
    "origin-x": 12,
    "origin-y": 5,
    "biome": ["shallow_water"]
  },
  {
    "name": "water_lily_2",
    "total-height": 2,
    "total-width": 2,
    "footprint-height": 1,
    "footprint-width": 2,
    "footprint-offset": 0,
    "origin-x": 14,
    "origin-y": 5,
    "biome": ["shallow_water"]
  },
  {
    "name": "water_lily_3",
    "total-height": 2,
    "total-width": 2,
    "footprint-height": 1,
    "footprint-width": 2,
    "footprint-offset": 0,
    "origin-x": 12,
    "origin-y": 7,
    "biome": ["shallow_water"]
  }

];
